language: c
compiler:
  - gcc

before_install: ./.travis/prepare.sh

env:
  - OPTS="--disable-ssl"

script: ./.travis/build.sh $OPTS

notifications:
  email:
    recipients:
      - secure: V7W+NdS3L1aXCMUo2EBmOIHeQHT76r78p3f25XFISz8D4a2FnXA2ydwQVbhiZxa+TRgrskY/iB5GU1fS70+qmIaGxnGAVRV8lIQVshoiaKuxvMcha0FdN4d44i1AmLiM2DK8r5k3+fEWTQCvq9mrXQnDJVEPpYfVGj5+b+9oBx8=
